### ISSUE TITLE
Support Uniswap v2

### ISSUE THREAD

**Issue by ErikBjare** [shanefontaine/uniswap-python#10]
I'm working on Uniswap v2 support (and a lot of other things) in my fork: https://github.com/ErikBjare/uniswap-python

Specifically this PR: https://github.com/ErikBjare/uniswap-python/pull/1

I'd be interested in getting it into upstream eventually, if that's of interest to you @shanefontaine

**Comment by shanefontaine** [comment]
I am very interested! If/when you think it is ready, I'll be glad to give it a review and then merge if ready.

Please make a PR when you feel appropriate.
