### ISSUE TITLE
How to sell?

### ISSUE THREAD

**Issue by ToniKuipers** [shanefontaine/uniswap-python#104]
Hi guys,

I try to use the make_trade_output or make_trade to sell a specific amout of tokens for ETH (in my case BNB). But both functions result in a buy and not a sell of the tokens. Am I using the feature incorrectly?? I have really tried all combinations but I can't figure it out.

```python
token_amount = wrapper.get_token_balance(token)
wrapper.make_trade_output(bnb,token,token_amount)    
```

or

```python
token_amount = wrapper.get_token_balance(token)
wrapper.make_trade(bnb,token,token_amount)    
```

**Comment by ErikBjare** [comment]
Switch the pair order.

You're misunderstanding the difference between plain `make_trade` and `make_trade_output`, they trade in the same direction (given the same argument order). The only difference is that in `make_trade` you specify the amount of token A to spend, and in `make_trade_output` you specify the amount of token B you want to receive.
