### ISSUE TITLE
Private key required for Uniswap() class

### ISSUE THREAD

**Issue by cmackeen** [shanefontaine/uniswap-python#16]
If I want to use some methods of the Uniswap() class, it seems I need to initialize a personal wallet address and private key. Shoul this be optional, that way it is only required for action-based methods?

**Comment by msujithk** [comment]
I think you need to provide private key only if you want to sign and send a transaction. You can do all other activities without providing a private key.

**Comment by ErikBjare** [comment]
Feel free to pass junk into `address` and `private_key` if you don't need them, or submit a PR that makes them optional (with the appropriate checks).

**Comment by ErikBjare** [comment]
This is now mentioned in the README: https://github.com/shanefontaine/uniswap-python/commit/b5f21fcbb18a537bf99a044e84c4b7fa31938fe7
