### ISSUE TITLE
Dependency issue when trying to install through pip

### ISSUE THREAD

**Issue by albertocastillo2001** [shanefontaine/uniswap-python#28]
Recently I tried to install the new package and got this issue though pip

`
ERROR: Could not find a version that satisfies the requirement rusty-rlp<0.2,>=0.1.15 (from rlp<=2.0.0.alpha-1,>=1.0.0->eth-account<0.6.0,>=0.5.3->web3<6.0.0,>=5.12.0->uniswap-python) (from versions: none)
ERROR: No matching distribution found for rusty-rlp<0.2,>=0.1.15 (from rlp<=2.0.0.alpha-1,>=1.0.0->eth-account<0.6.0,>=0.5.3->web3<6.0.0,>=5.12.0->uniswap-python)
`

**Comment by albertocastillo2001** [comment]
I have tried two versions of the Python interpreter and ran into the same issue, 3.7 and 3.8 (I don't see a reason why this should happen tho

**Comment by ErikBjare** [comment]
Platform? Works fine when installing with pip on my machine, and in CI.

**Comment by albertocastillo2001** [comment]
Sorry, it's a Windows 10 64 bit. Also tried on a Windows Server 2012 R2 as well

**Comment by ErikBjare** [comment]
Can you install web3 without issue? From the error it looks like it isn't an issue with uniswap-python but rather a downstream dependency of web3.

**Comment by ErikBjare** [comment]
Closing since it's not an issue with uniswap-python itself.
