### ISSUE TITLE
cannot get price for uni

### ISSUE THREAD

**Issue by oracle707** [shanefontaine/uniswap-python#33]
I added 
`uni='0x1f9840a85d5af5bf1d1762f925bdaddc4201f984'`
contract number taken from https://www.coingecko.com/en/coins/uniswap
and use `uniswap_wrapper.get_eth_token_input_price(uni, 1*10**18)` function
have a long error explanation with 

```
web3.exceptions.InvalidAddress: ('Address has an invalid EIP-55 checksum. After looking up the address from the original source, try again.', '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984')
```

in the end

**Comment by ErikBjare** [comment]
Use the checksummed version of the address: `0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984`
