### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by ShilazTech** [shanefontaine/uniswap-python#38]
Receiving error while using the library as below
from uniswap import uniswap
account_1="..."
private_key="..."
uniswap_wrapper = uniswap(account_1, private_key, version=2)  # pass version=2 to use Uniswap

the error is 

" uniswap_wrapper = uniswap(account_1, private_key, version=2)  # pass version=2 to use Uniswap
TypeError: 'module' object is not callable"

pls advise the solution

**Comment by ErikBjare** [comment]
Your import statement is incorrect. It needs to be `from uniswap import Uniswap`.
