### ISSUE TITLE
AttributeError: module 'uniswap' has no attribute 'UniswapWrapper'

### ISSUE THREAD

**Issue by kwikiel** [shanefontaine/uniswap-python#4]
AttributeError: module 'uniswap' has no attribute 'UniswapWrapper' when trying to execute the following code:

import uniswap
uniswap_wrapper = uniswap.UniswapWrapper()
eth = "0x0000000000000000000000000000000000000000"
bat = "0x0D8775F648430679A709E98d2b0Cb6250d2887EF"
dai = "0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359"

https://pypi.org/project/uniswap-python/

**Comment by shanefontaine** [comment]
Thank you!

Closed with 91d7877a9c6afda2f7c8b544c2f44a922d6ab023.
