### ISSUE TITLE
How to setup provider with IPC

### ISSUE THREAD

**Issue by TomOerlemans** [shanefontaine/uniswap-python#43]
I am running a local geth node. The following works:

```
from web3 import Web3
w3 = Web3(Web3.IPCProvider("//root/.ethereum/geth.ipc"))
w3.eth.blockNumber

```
However, this does not work:

```
from uniswap import Uniswap
import os
os.environ["PROVIDER"] = "//root/.ethereum/geth.ipc" // Here I am setting the provider environment variable
address = "0x0000000000000000000000000000000000000000"    
private_key = None
uniswap_wrapper = Uniswap(address, private_key, version=2)
```

I have tried various variations of formatting the provider string, but I keep on getting errors, such as:

> MissingSchema: Invalid URL '//root/.ethereum/geth.ipc': No schema supplied.
Or
> InvalidSchema: No connection adapters were found for 'ipc://root/.ethereum/geth.ipc'

Any advice on how to get this to work?

**Comment by ErikBjare** [comment]
The library assumes that the PROVIDER environment variable is an HTTP provider.

Since you closed the issue I assume you solved it yourself, but you could have done:

```
from web3 import Web3
w3 = Web3(Web3.IPCProvider("//root/.ethereum/geth.ipc"))
uniswap_wrapper = Uniswap(address, private_key, version=2, web3=w3)
```
