### ISSUE TITLE
Can't get all tokens

### ISSUE THREAD

**Issue by Wigbill** [shanefontaine/uniswap-python#45]
Code is:
```py
from dotenv import load_dotenv
import os

from pathlib import Path
from pprint import pprint

from uniswap import Uniswap


env_path = Path('.') / '.env'
load_dotenv(dotenv_path=env_path)

ADDRESS = os.getenv("ADDRESS")
PRIVATE_KEY = os.getenv("PRIVATE_KEY")

uniswap_wrapper = Uniswap(ADDRESS, PRIVATE_KEY, version=1)

eth = "0x0000000000000000000000000000000000000000"
bat = "0x0D8775F648430679A709E98d2b0Cb6250d2887EF"
dai = "0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359"

pprint(uniswap_wrapper.get_all_tokens())
```

Error:
`uniswap.uniswap.InvalidToken: Invalid token address: 0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2`

**Comment by ErikBjare** [comment]
The `get_all_tokens` method isn't really supported (it accidentally slipped into a commit) and I have no plans to make it work reliably. 

Most likely the contract at that address doesn't follow the ERC20 spec. If you turn on logging you should get better output:

```py
import logging
logging.basicConfig(level=logging.INFO)
```

I'm sorry to say it, but you're on your own. Feel free to submit a PR if you fix it.
