### ISSUE TITLE
Forbid transfering currency

### ISSUE THREAD

**Issue by monk-after-90s** [shanefontaine/uniswap-python#47]
I want to only swap currencies rather than to transfer currencies. How to manage such authority?

**Comment by ErikBjare** [comment]
Not sure what you are asking, but assuming I understand you correctly: To my knowledge, the only way to do this is to create a proxy contract (which holds all assets) and has an endpoint for swapping that can be allowed to be called by a third address.

Regardless, this is not the right place to ask, as it has nothing to do with the library itself. Closing.

**Comment by monk-after-90s** [comment]
> Not sure what you are asking, but assuming I understand you correctly: To my knowledge, the only way to do this is to create a proxy contract (which holds all assets) and has an endpoint for swapping that can be allowed to be called by a third address.
> 
> Regardless, this is not the right place to ask, as it has nothing to do with the library itself. Closing.

Hah, forgive me while I am new to ETH. 

I mean my friend wants me to make transactions through uniswap, but he never wants me to transfer the assets away and run away, hah hah. Like api authority management in centralized exchanges, he wants me to use a limited UNISWAP api. Or limit the target  addresses to transfer assets?

**Comment by ErikBjare** [comment]
As I said, you can't do that easily (the approach I mentioned would work, although if you're new to ETH it'll be a *really* bad idea). 

Ask somewhere else, this is not a general support forum for ETH. (and please read: http://www.catb.org/~esr/faqs/smart-questions.html)
