### ISSUE TITLE
install uniswap-python error

### ISSUE THREAD

**Issue by monkeyip** [shanefontaine/uniswap-python#48]
My python env:
python 3.7.0

when I "pip install uniswap-python"，the error is below:
**Could not find a version that satisfies the requirement ipfshttpclient==0.7.0a1**

I think whether the python's version is not true?
I see the pkg:  ipfshttpclient==0.7.0a1 is a pre-release version.

please help me, thank you!!!

**Comment by ErikBjare** [comment]
It installs fine for me with Python 3.8.4:

```
Collecting ipfshttpclient==0.7.0a1
  Downloading ipfshttpclient-0.7.0a1-py3-none-any.whl (231 kB)
     |████████████████████████████████| 231 kB 13.0 MB/s
```

However, on the PyPI page for the package it says: 

>Requires: Python >=3.5.4, !=3.6.0, !=3.6.1, !=3.7.0, !=3.7.1

So, you need to update your Python version to 3.7.2 or above.
