### ISSUE TITLE
big price difference: API vs web

### ISSUE THREAD

**Issue by brent-virgox** [shanefontaine/uniswap-python#50]
For some tokens with ample liquidity and volume, I am seeing big differences between price returned by get_token_token_input_price and the uniswap web application. Specifically, price impact implied by API returns is significantly larger. 

For example, ESD -> USDC trade. for 10 ESD, API returned 9.08 USDC while web returned 9.89 USDC; for 100 ESD, API returned 47.86 USDC while web returned 98.9. i.e. price impact implied by API returns was ~50%, while that of web returns was almost none. 

Can anyone shine some light on this question?

**Comment by ErikBjare** [comment]
Are you passing `version=2` to the constructor? Liquidity on Uniswap v1 is pretty bad...

**Comment by brent-virgox** [comment]
> 
> 
> Are you passing `version=2` to the constructor? Liquidity on Uniswap v1 is pretty bad...
> 
> Could also be a case where using ETH pools for liquidity isn't ideal (we assume the best route for token-token swaps is token-ETH-token).
> 
> Edit: From the looks of it that seems to be the case. The ESD-ETH pair has almost no liquidity (https://info.uniswap.org/pair/0x4acdb58fd79556cd276a08ec2e599d48a1ac6290), the ESD-USDC on the other hand has quite a bit.

Thanks! It makes a lot of sense. The output was good after I overwrote the routing path. 
Is there a way we can replicate the way uniswap optimizes routing path?
