### ISSUE TITLE
make trade questions

### ISSUE THREAD

**Issue by albertocastillo2001** [shanefontaine/uniswap-python#51]
Hello
I am quite new to w3 and uniswap-python

I have managed to follow some of the examples retrieving price of some tokens, using checksum versions of the contract names, etc.

However I have certain questions regarding make_trade. How to specify the quantity and why such format.

What if I want to specify an exact ammount of ETH and tokens with certain slippage and gas adjusting at aspecific price. Just imagine if the price moves heavily just when you are trying to get in. Are also more examples about it available?

Thank you.

**Comment by MarkWh1te** [comment]
@albertocastillo2001 
`What if I want to specify an exact amount of ETH and tokens with certain slippage and gas adjusting at an aspecific price. Just imagine if the price moves heavily just when you are trying to get in. Are also more examples about it available?`
Currently not, but I believe you can't do it even if you are using the web version of UNISWAP.
Furthermore, I highly recommend you read something about [how UNISWAP works](https://medium.com/coinmonks/how-does-uniswap-work-75765c4640e0#:~:text=Uniswap%20is%20an%20Ethereum%20based,Uniswap%20creates%20markets%20automatically.).
