### ISSUE TITLE
[help needed] get_token_eth_output_price spitting huge values

### ISSUE THREAD

**Issue by brah** [shanefontaine/uniswap-python#56]
I'm working on a very lightweight discord bot, and just need a simple command to check the price of a token on uniswap.
I've come up with
`    prq_val = uniswap_wrapper.get_token_eth_output_price("0x362bc847A3a9637d3af6624EeC853618a43ed7D2", 1*10**18)`
as seen in your documentation, and getting a return of "1059715878516377184220" and other numbers in similar ranges. I imagine the error is blindingly obvious, and I gather it's to do with the parameters, but I'll be going around in circles for hours if I didn't just ask. Appreciate it!

**Comment by ErikBjare** [comment]
This has been asked and answered before, see for example: https://github.com/shanefontaine/uniswap-python/issues/12
