### ISSUE TITLE
Add support for instatiating Uniswap class without supplying address and private key

### ISSUE THREAD

**Issue by ErikBjare** [shanefontaine/uniswap-python#60]
It's quite common to want to use the class to merely get price info and similar, for which an address and private key isn't needed. 

We should probably add the ability for users to instantiate the class without them. My current workaround is to simply use `0x0000000000000000000000000000000000000000` as the address and `0x0000000000000000000000000000000000000000000000000000000000000000` as the priv key.

**Comment by MarkWh1te** [comment]
Sounds like a cool idea. 
And it seems very easy to implement. 
Just add two default values in the `__init__ ` method?
