### ISSUE TITLE
Can't get ETH-USDT price from uniswap .

### ISSUE THREAD

**Issue by MarkWh1te** [shanefontaine/uniswap-python#61]
Thanks, @shanefontaine  for the great work. 
I have a humble problem. I can't get ETH-USDT price from UNISWP.
There is code:

```Python
    dai = Web3.toChecksumAddress("0x0e2298E3B3390e3b945a5456fBf59eCc3f55DA16")
    usdt = Web3.toChecksumAddress("0xdac17f958d2ee523a2206206994597c13d831ec7")
    uniswap_wrapper = Uniswap(address, private_key, version=2, web3=w3)
    print(f"{round(uniswap_wrapper.get_eth_token_input_price(dai, 1 * 10 ** 18) / 10 ** 18, 6)}") # works 
    print(f"{round(uniswap_wrapper.get_eth_token_output_price(dai, 1 * 10 ** 18) / 10 ** 18, 6)}") # works 

    print(f"{round(uniswap_wrapper.get_eth_token_input_price(usdt, 1 * 10 ** 18) / 10 ** 18, 6)}") # doesn't work
    print(f"{round(uniswap_wrapper.get_eth_token_output_price(usdt, 1 * 10 ** 18) / 10 ** 18, 6)}") # doesn't work

```

**Comment by ErikBjare** [comment]
What do you mean "doesn't work"? What's the error?

It is important to note that the USDT contract uses 6 decimals, not 18 as in your code. See, for example, issue https://github.com/shanefontaine/uniswap-python/issues/12 where someone had a similar issue.

**Comment by MarkWh1te** [comment]
@ErikBjare Thanks for the quick reply! 
You are right, I made a mistake on decimals. 
I will close this issue. 
Thank you very much!
