### ISSUE TITLE
Is there any way we can set transaction parameters?

### ISSUE THREAD

**Issue by MarkWh1te** [shanefontaine/uniswap-python#63]
Correct me if I'm wrong. So, I have noticed that there is only `_get_tx_params` but no `_set_tx_params`. May I ask is there any way we can set transaction parameters?

https://github.com/shanefontaine/uniswap-python/blob/f24993bcea8cb4181be59dd7e4e9abcd40a375cb/uniswap/uniswap.py#L768

**Comment by ErikBjare** [comment]
You could always monkey-patch the `_get_tx_params` method. I don't really see the use though?

**Comment by MarkWh1te** [comment]
> You could always monkey-patch the `_get_tx_params` method. I don't really see the use though?
 
For example, I want to make a transaction with a very high gas fee.

**Comment by ErikBjare** [comment]
The gas price is not set using the transaction parameters (only the gas
limit).

Gas price is set by configuring Web3:
https://web3py.readthedocs.io/en/stable/gas_price.html

**Comment by MarkWh1te** [comment]
```
Gas price is set by configuring Web3:
https://web3py.readthedocs.io/en/stable/gas_price.html
```
Thank you very much. It works!
