### ISSUE TITLE
Quickswap support 

### ISSUE THREAD

**Issue by Tobias35** [shanefontaine/uniswap-python#67]
hello 
quickswap is a uniswap fork running on matic network. 
would be cool if we could use this wrapper for quickswap on almost gasfree L2.

pls respond :)

**Comment by ErikBjare** [comment]
This would be easy to fix if we make the changes I suggest in https://github.com/shanefontaine/uniswap-python/pull/58#issuecomment-763469814

**Comment by ErikBjare** [comment]
Should be possible now in the latest commit on master, see https://github.com/shanefontaine/uniswap-python/issues/90#issuecomment-831896252.
