### ISSUE TITLE
get_token_eth_input_price convert issue

### ISSUE THREAD

**Issue by hzqandy123** [shanefontaine/uniswap-python#68]
I used the method get_token_eth_input_price ,  the result was  incorrect ， example： eth price is 1447.47usdt , the  method return result is 1477542387  How to convert the output result  to 1447.47  

thank you very much for your reply

**Comment by ErikBjare** [comment]
You need to account for the number of decimals for the USDT token.

See the many other closed issues where people are asking about the same
thing.
