### ISSUE TITLE
Trouble getting correct price for get_eth_token_input_price with low liquidity coins

### ISSUE THREAD

**Issue by Drblessing** [shanefontaine/uniswap-python#71]
See attached screenshots,

the price the function gives me appears 4% off. 

Applying the method to Akro_weth pair with approximately $748k liquidity at approximately 4 PM EST 
https://info.uniswap.org/pair/0x8cb77ea869def8f7fdeab9e4da6cf02897bbf076

Akro reserves: 9_292_272

WETH reserves: 209.799

Output method get_eth_token_input_price is giving me: **441584**

Output uniswap UI says: **421551**

Calculated it by hand to check and it agreed with uni swap UI.

Does anyone know what's going on? 

![image](https://user-images.githubusercontent.com/52829488/110381516-678b1e00-800e-11eb-8d4d-66e401dddb2b.png)

![image](https://user-images.githubusercontent.com/52829488/110381550-770a6700-800e-11eb-9359-4aa364a5691c.png)

![image](https://user-images.githubusercontent.com/52829488/110381591-88537380-800e-11eb-9ec9-5d2f3fcbd1ee.png)

**Comment by ErikBjare** [comment]
Nope, it works just as expected, you just have a mistake in your code: It
asks for how many 10**-18 AKRO you get for 10 Wei, not for 10 ETH (1 ETH =
10**18 Wei). The entire difference is due to price slippage.

Closing.

**Comment by Drblessing** [comment]
Thank you very much.
