### ISSUE TITLE
Formulas 

### ISSUE THREAD

**Issue by YaProstoUmniy** [shanefontaine/uniswap-python#75]
![image](https://user-images.githubusercontent.com/72607883/111820683-744f2200-88ea-11eb-8b37-d83e5b93505b.png)

what value i need to set for USDT?
And how i can know price,for pairs for example?
or price for ETH in USDT?

**Comment by YaProstoUmniy** [comment]
and what that numbers meant?

**Comment by ErikBjare** [comment]
Duplicate. Read the other issues like #61. 

Closing.
