### ISSUE TITLE
from uniswap import Uniswap ERROR

### ISSUE THREAD

**Issue by eosfomogame** [shanefontaine/uniswap-python#81]
**from uniswap import Uniswap**

`ImportError: cannot import name 'Uniswap'`

This is very strange

**Comment by ErikBjare** [comment]
This is not enough detail to be a useful bug report. We need considerably more detail (how did you install, how can we reproduce, etc).

**Comment by olegkre** [comment]
Have same Problem
fresh install Ubuntu 18 64bit

apt-get update
apt install python3-pip
alias pip=pip3
pip install uniswap-python

root@ubuntu:~# python3 
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from uniswap import Uniswap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Uniswap'
>>> 

what can i do please help
