### ISSUE TITLE
Failed to establish a new connection 

### ISSUE THREAD

**Issue by viktor-settlemint** [shanefontaine/uniswap-python#82]
Hi, I am trying to use the wrapper to fetch my balances, when I put my metamask address and private key I have an error I this specific line of code: `uniswap_wrapper = (address, private_key, version=2) `, I have the following error message:

`ConnectionError: HTTPConnectionPool(host='web3', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3786cf4910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))`

**Comment by ErikBjare** [comment]
Read the README more carefully, you've probably set `PROVIDER` incorrectly.
