### ISSUE TITLE
InvalidAdress: Web3.py only accepts checksum

### ISSUE THREAD

**Issue by viktor-settlemint** [shanefontaine/uniswap-python#83]
I followed the README, I am trying to fetch the balance of USDC/ETH, I did the following:
```
from uniswap import Uniswap
address="0x0000000000000000000000000000000000000000"
private_key="None"
uniswap_wrapper=Uniswap(address,private_key, version=1)
usdc="0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48" 
uniswap_wrapper.get_ex_token_balance(usdc)
```

I have then the following error message:
`InvalidAddress: ('Web3.py only accepts checksum addresses. The software that gave you this non-checksum address should be considered unsafe, please file it as a bug on their platform. Try using an ENS name instead. Or, if you must accept lower safety, use Web3.toChecksumAddress(lower_case_address).', '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48')`

And if I do ` uniswap_wrapper.get_ex_eth_balance(usdc)` I have the same. Can you point me the issue? thankn you

**Comment by viktor-settlemint** [comment]
I took the address from Uniswap app: https://v1.uniswap.info/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
but when I take from the contract address on etherscan then it works

**Comment by viktor-settlemint** [comment]
There is basically Web3.toChecksumAddress which needs to be added, but then it does not return the right balance

**Comment by liquid-8** [comment]
i.e.
`uniswap_wrapper.get_ex_token_balance(uniswap_wrapper.w3.toChecksumAddress(usdc))`

**Comment by ErikBjare** [comment]
As the error clearly states, you need to use the checksummed version of the address. 

This is the intended behavior and won't be changed.

**Comment by viktor-settlemint** [comment]
@ErikBjare what's the point to have that? I don't get it

**Comment by ErikBjare** [comment]
It prevents mistyping addresses, see the rationale in EIP-55: https://github.com/ethereum/EIPs/issues/55
