### ISSUE TITLE
Exception: Unknown netid: 3 with Ropsten Infura Node

### ISSUE THREAD

**Issue by nacho7592** [shanefontaine/uniswap-python#84]
I'm trying to use a Ropsten Infura Node as Provider while creating the Uniswap object and i get that exception raised.
Could you give some point of advice on this? 
Thanks!

**Comment by nacho7592** [comment]
Hi,
I fix that just adding Ropsten to the dict of netids.

 _netid_to_name = {1: "mainnet",3: 'ropsten', 4: "rinkeby"}

**Comment by albertocastillo2001** [comment]
So far it would be nice to have ropsten available by default. As there are more faucets around @ErikBjare 
Thank you.

**Comment by ErikBjare** [comment]
@albertocastillo2001 If you make a PR I'll merge it!
