### ISSUE TITLE
Fail with error 'PancakeLibrary: IDENTICAL_ADDRESSES'

### ISSUE THREAD

**Issue by ToniKuipers** [shanefontaine/uniswap-python#96]
First of all, great work! I used the information from #90 to use PancakeSwap for swapping. Unfortunately I run into a problem. On the BSCSCAN I get the following error: Fail with error 'PancakeLibrary: IDENTICAL_ADDRESSES'. See the link below to the transaction. https://bscscan.com/tx/0x813d526c880bd289fe1f6c205989358b3c08247f1c9c3bd3cbc2de4ef117e7b4. Is there anyone who can help me?

```py
from decimal import *
from web3 import Web3
from uniswap import Uniswap
w3 = Web3(Web3.HTTPProvider("https://bsc-dataseed1.binance.org:443"))

address = "private"
private_key = "private"
bnb = w3.toChecksumAddress("0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c")
token = w3.toChecksumAddress("0X4E6415A5727EA08AAE4580057187923AEC331227")
buy_price = w3.toWei(Decimal('0.01'), 'ether')                                         #0.01 BNB


pcs_wrapper = Uniswap(address, private_key, version=2)
pcs_wrapper.make_trade(token, bnb, buy_price)
```

As you may see I am still a beginner :)

**Comment by liquid-8** [comment]
Long story short, there is no quick solution. make_trade(...) should be reworked some way due alternate network support. In your case, there was swapExactTokensForTokens(...) call instead of swapExactTokensForETH(...). BNB is analogue for ETH on bsc network so make_trade(...) have to compare input_token/output_token params with BNB's contract (actiually, self.router.WETH() ) to determine proper calls.

**Comment by thojdid** [comment]
Hey guys,
I also adapted the library to make it work with BSC.
Thanks liquid-8 for your clue.
Indeed, in uniswap.py, just replace the line 
ETH_ADDRESS = "0x0000000000000000000000000000000000000000"
by
ETH_ADDRESS = "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
(which is actually the address of WBNB)
and it might work.

**Comment by ToniKuipers** [comment]
@thojdid That worked for me! Thanks!

**Comment by Theagainmen** [comment]
@ToniKuipers can I send you a message somewhere on Telegram or Discord? I have some questions about how you got this wrapper working with PancakeSwap. Thanks in advance!

**Comment by qraxiss** [comment]
@Theagainmen Did you manage to work with other exchanges?
