### ISSUE TITLE
How to modify gas price? (set_gas_price_strategy)

### ISSUE THREAD

**Issue by ToniKuipers** [shanefontaine/uniswap-python#99]
I try to modify the gas price by using the set_gas_price_strategy function of Web3. Unfortunately, I get the error below:

return self.gasPriceStrategy(self.web3, transaction_params)
TypeError: 'int' object is not callable

Can someone help me? :)

`from decimal import *
from web3 import Web3
from pancakeswap import PancakeSwap

w3 = Web3(Web3.HTTPProvider("https://bsc-dataseed1.binance.org:443"))

address = "private"
private_key = "private"
bnb = w3.toChecksumAddress("0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c")
token = w3.toChecksumAddress("0x4e6415a5727ea08aae4580057187923aec331227")

buy_price = w3.toWei(Decimal('5'), 'ether')
w3.eth.set_gas_price_strategy(w3.toWei(20, 'gwei'))

pcs_wrapper = PancakeSwap(address, private_key, web3=w3, version=2, max_slippage=0.1)
pcs_wrapper.make_trade(token, bnb, buy_price)'

**Comment by ErikBjare** [comment]
Read the Web3py docs more carefully, you're not using it correctly.

And please don't open an issue for every small thing you need help with. It's really overwhelming as a maintainer to have to deal with many small questions like this. 

If you have an issue you really can't solve yourself, then that's okay, but please put some more effort in first, and when you do open an issue include things like stacktraces, what you've tried to fix it, etc.

I recommend reading:

 - http://www.catb.org/~esr/faqs/smart-questions.html
 - https://stackoverflow.com/help/how-to-ask
